// SPDX-License-Identifier: Apache-2.0
/**
 * Regenerate the skill's chain and protocol reference tables from the live API.
 *
 * Both files claimed to be "generated from GET /v1/chains" for a month while no
 * generator existed, so they were hand-written and went stale the moment LI.FI
 * indexed anything new — 16 chains became 19 and 13 protocols became 27 without
 * a word changing. Agents read these files; a stale table there is worse than
 * no table, because it looks authoritative.
 *
 *   LIFI_API_KEY=... pnpm --filter @earnforge/sdk generate:refs
 */
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { EarnDataClient } from '../src/clients/index.js'
import { PROTOCOL_TIERS } from '../src/risk-scorer.js'

const REFS = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../../skills/earnforge/references'
)

const today = new Date().toLocaleDateString('en-US', {
  month: 'short',
  day: 'numeric',
  year: 'numeric',
})

const client = new EarnDataClient()

const [chains, protocols] = await Promise.all([
  client.listChains(),
  client.listProtocols(),
])

// ── chains.md ──────────────────────────────────────────────────────────

const chainRows = [...chains]
  .sort((a, b) => a.chainId - b.chainId)
  .map((c) => `| \`${c.chainId}\` | ${c.name} | \`${c.networkCaip}\` |`)
  .join('\n')

writeFileSync(
  `${REFS}/chains.md`,
  `# Chains

Chains with at least one indexed Earn vault. Generated from
\`GET https://earn.li.fi/v1/chains\` — never hardcode this list, it changes.

${chains.length} chains as of ${today}.

Chain ids are numbers. The single-vault endpoint is
\`/v1/vaults/:chainId/:address\` and a chain *name* there returns 400.

| Chain ID | Name | CAIP-2 |
|---|---|---|
${chainRows}

<!-- Generated by packages/sdk/scripts/generate-references.ts — do not edit. -->
`
)

// ── protocols.md ───────────────────────────────────────────────────────

const versioned = protocols
  .map((p) => p.id ?? p.name)
  .filter((id) => /-v\d+$/.test(id))

const protocolRows = [...protocols]
  .sort((a, b) => (a.id ?? a.name).localeCompare(b.id ?? b.name))
  .map((p) => {
    const id = p.id ?? p.name
    const tier = PROTOCOL_TIERS[id]
    return `| \`${id}\` | ${tier ?? '3 (default)'} | ${p.url} |`
  })
  .join('\n')

const untiered = protocols
  .map((p) => p.id ?? p.name)
  .filter((id) => !(id in PROTOCOL_TIERS))

writeFileSync(
  `${REFS}/protocols.md`,
  `# Protocols

Protocols with at least one indexed Earn vault. Generated from
\`GET https://earn.li.fi/v1/protocols\`.

${protocols.length} protocols as of ${today}.

**Read ids from the endpoint; never hardcode them.** Most are unversioned
(\`morpho\`, not \`morpho-v1\`), but that is a convention rather than a rule —
${
  versioned.length > 0
    ? `${versioned.map((v) => `\`${v}\``).join(', ')} ${
        versioned.length === 1 ? 'is' : 'are'
      } versioned today.`
    : 'no protocol is versioned today, though some have been.'
}
Filtering on an id that no longer exists returns HTTP 200 with zero results,
not an error, so a stale id is indistinguishable from an empty protocol.

| Id | Risk tier (0-10) | URL |
|---|---|---|
${protocolRows}
${
  untiered.length > 0
    ? `\nProtocols with no explicit tier fall back to 3: ${untiered
        .map((u) => `\`${u}\``)
        .join(', ')}.\n`
    : '\nEvery live protocol carries an explicit risk tier.\n'
}
<!-- Generated by packages/sdk/scripts/generate-references.ts — do not edit. -->
`
)

console.warn(
  `Wrote chains.md (${chains.length}) and protocols.md (${protocols.length})` +
    (untiered.length > 0 ? ` — ${untiered.length} untiered` : ' — all tiered')
)
